version: '3'

services:
  api:
    build:
      context: .
    restart: always
    container_name: api
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    env_file:
      - .env
    links:
      - mysql
      - redis
    tty: true
    entrypoint: /bin/bash

  migration:
    build:
      context: .
    container_name: migration
    volumes:
      - .:/app
    env_file:
      - .env
    links:
      - mysql
      - redis
    entrypoint: python manage.py migrate

  mysql:
    image: "mysql:8"
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - "3306:3306"
    volumes:
    - /Users/apple/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "plantsmart"

  redis:
    image: "redis:latest"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"